#ifndef NSOCK_TEST_H
#define NSOCK_TEST_H

#define TCP_HOST_VALID 		"qoop.org:80"
#define TCP_HOST_INVALID 	"bad.:80"
#define TCP_HOST_INVALID_PORT 	"127.0.0.1:bad."
#define TCP_HOST_NO_ROUTE 	"192.168.254.254:80"
#define TCP_HOST_BIND_FAILS 	"qoop.org:3133"
#define TCP_HOST_LOCAL_UNUSED 	"127.0.0.1:6423"
#define TCP_HOST_LOCAL_INUSE 	"127.0.0.1:6000"
#define TCP_HOST_WRAPPED 	"elite.net:22"
#define TCP_HOST_BANNER 	"qoop.org:21"


#define UNIX_SOCK_NAME 		"wtf.sock"
#define UNIX_PATH_SHORT 	"/tmp"
#define UNIX_PATH_128A 		"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
#define UNIX_PATH_LONG 		UNIX_PATH_SHORT "/" UNIX_PATH_128A
#define UNIX_SOCK_SHORT 	UNIX_PATH_SHORT "/" UNIX_SOCK_NAME
#define UNIX_SOCK_LONG 		UNIX_PATH_LONG "/" UNIX_SOCK_NAME
#define UNIX_PATH_TOO_LONG 	UNIX_PATH_LONG "/" \
   UNIX_PATH_128A "/" UNIX_PATH_128A "/" UNIX_PATH_128A "/" UNIX_PATH_128A "/" \
   UNIX_PATH_128A "/" UNIX_PATH_128A "/" UNIX_PATH_128A "/" UNIX_PATH_128A "/" \
   UNIX_PATH_128A "/" UNIX_PATH_128A "/" UNIX_PATH_128A "/" UNIX_PATH_128A "/" \
   UNIX_PATH_128A "/" UNIX_PATH_128A "/" UNIX_PATH_128A "/" UNIX_PATH_128A "/" \
   UNIX_PATH_128A "/" UNIX_PATH_128A "/" UNIX_PATH_128A "/" UNIX_PATH_128A "/" \
   UNIX_PATH_128A "/" UNIX_PATH_128A "/" UNIX_PATH_128A "/" UNIX_PATH_128A "/" \
   UNIX_PATH_128A "/" UNIX_PATH_128A "/" UNIX_PATH_128A "/" UNIX_PATH_128A "/" \
   UNIX_PATH_128A "/" UNIX_PATH_128A "/" UNIX_PATH_128A "/" UNIX_PATH_128A
#define UNIX_SOCK_PATH_TOO_LONG	UNIX_PATH_TOO_LONG "/" UNIX_SOCK_NAME
#define UNIX_SOCK_TOO_LONG 	UNIX_PATH_128A
#define UNIX_SOCK_SOCK_TOO_LONG UNIX_PATH_SHORT "/" UNIX_SOCK_TOO_LONG

#endif
